//! Integration test: run `noise_model.espdl` end-to-end with scalar kernels
//! using golden OFF/ON INT8 inputs generated by the Python export.

extern crate edgedl_macros;

// Bind the model from the embedded .espdl file
#[edgedl_macros::espdl_model(path = "tests/noise_model.espdl")]
struct __ModelBind;

// Bring in the golden OFF/ON inputs (already engine-quantized INT8 in NHWC order)
#[path = "golden_inputs.rs"]
mod golden;

use std::sync::Once;
static INIT: Once = Once::new();
fn init_logging() {
    INIT.call_once(|| {
        let _ = env_logger::builder()
            .is_test(true)
            .filter_module("edgedl", log::LevelFilter::Debug)
            .try_init();
    });
}

fn argmax_f32(xs: &[f32]) -> usize {
    let mut best_i = 0usize;
    let mut best_v = f32::NEG_INFINITY;
    for (i, &v) in xs.iter().enumerate() {
        if v > best_v {
            best_v = v;
            best_i = i;
        }
    }
    best_i
}

#[test]
fn noise_model_off_on_from_golden_inputs() {
    init_logging();
    // Validate input layout and expected dimensions
    assert!(
        __ModelBind::SPEC.inputs.len() == 1,
        "expected single-input model"
    );
    let in_id = __ModelBind::SPEC.inputs[0];
    let in_meta = __ModelBind::SPEC.values[in_id as usize];
    let need = in_meta.shape.elements();

    assert_eq!(
        golden::GOLDEN_OFF_INPUT_I8.len(),
        need,
        "OFF golden length != input elements"
    );
    assert_eq!(
        golden::GOLDEN_ON_INPUT_I8.len(),
        need,
        "ON golden length != input elements"
    );

    // Prepare probabilities buffer sized to the first model output tensor
    let out0_id = __ModelBind::SPEC.outputs[0];
    let out0_meta = __ModelBind::SPEC.values[out0_id as usize];
    assert_eq!(out0_meta.shape.n as usize, 1, "N != 1");
    let mut probs: Vec<f32> = vec![0.0; out0_meta.shape.elements()];
    // Create runtime over a reusable arena buffer
    let mut arena = vec![0i8; __ModelBind::ARENA_SIZE];
    let mut rt = __ModelBind::new(&mut arena[..]).expect("runtime new");

    // OFF -> expect class 0 (also compute probabilities)
    rt.predict(&golden::GOLDEN_OFF_INPUT_I8, &mut probs)
        .expect("predict off");
    let off_label = argmax_f32(&probs);
    eprintln!("OFF probs : {:?}", probs);

    // ON -> expect class 1
    for v in probs.iter_mut() {
        *v = 0.0;
    }
    rt.predict(&golden::GOLDEN_ON_INPUT_I8, &mut probs)
        .expect("predict on");
    let on_label = argmax_f32(&probs);
    eprintln!("ON  probs : {:?}", probs);

    eprintln!("labels: off={} on={}", off_label, on_label);

    assert_eq!(out0_meta.shape.elements(), 2, "expected 2-class logits");
    assert_eq!(off_label, 0, "OFF sample should predict class 0");
    assert_eq!(on_label, 1, "ON sample should predict class 1");
}
